/* -*- C++ -*- */
/* Generated by opendds_idl version 3.34.0-dev (ACE version 6.5.22) running on input file Basic_Message.idl */
#ifndef OPENDDS_IDL_GENERATED_BASIC_MESSAGETYPESUPPORTIMPL_H_OHXLJO
#define OPENDDS_IDL_GENERATED_BASIC_MESSAGETYPESUPPORTIMPL_H_OHXLJO

#include <dds/Version.h>
#if !OPENDDS_VERSION_EXACTLY(3, 34, 0)
#  error "This file should be regenerated with opendds_idl"
#endif
#include <dds/DCPS/Definitions.h>

#include <dds/DdsDcpsC.h>

#include "Basic_MessageC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/ValueReader.h"
#include "dds/DCPS/ValueWriter.h"
#include "dds/DCPS/XTypes/DynamicDataAdapter.h"
#include "dds/DCPS/XTypes/TypeObject.h"
#include "Hello_Export.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: Hello */



/* Begin STRUCT: Basic_Message */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct Hello_Basic_Message_xtag {};
template<> Hello_Export
const XTypes::TypeIdentifier& getMinimalTypeIdentifier<Hello_Basic_Message_xtag>();

template<> Hello_Export
const XTypes::TypeMap& getMinimalTypeMap<Hello_Basic_Message_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

Hello_Export
bool vread(OpenDDS::DCPS::ValueReader& value_reader,  ::Hello::Basic_Message& value);

Hello_Export
bool vread(OpenDDS::DCPS::ValueReader& value_reader, const NestedKeyOnly< ::Hello::Basic_Message>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

Hello_Export
bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const  ::Hello::Basic_Message& value);

Hello_Export
bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const NestedKeyOnly<const  ::Hello::Basic_Message>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> Hello_Export
void set_default( ::Hello::Basic_Message& stru);

Hello_Export
void serialized_size(const Encoding& encoding, size_t& size, const ::Hello::Basic_Message& stru);

Hello_Export
bool operator<<(Serializer& strm, const ::Hello::Basic_Message& stru);

Hello_Export
bool operator>>(Serializer& strm,  ::Hello::Basic_Message& stru);

Hello_Export
void serialized_size(const Encoding& encoding, size_t& size, const NestedKeyOnly<const ::Hello::Basic_Message>& stru);

Hello_Export
bool operator<<(Serializer& strm, const NestedKeyOnly<const ::Hello::Basic_Message>& stru);

Hello_Export
bool operator>>(Serializer& strm, const NestedKeyOnly< ::Hello::Basic_Message>& stru);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
Hello_Export
const MetaStruct& getMetaStruct< ::Hello::Basic_Message>();
Hello_Export
bool gen_skip_over(Serializer& ser,  ::Hello::Basic_Message*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
Hello_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::Hello::Basic_Message,  ::Hello::Basic_Message>(DDS::DynamicType_ptr type, const  ::Hello::Basic_Message& value);

template <>
Hello_Export DDS::DynamicData_ptr get_dynamic_data_adapter< ::Hello::Basic_Message,  ::Hello::Basic_Message>(DDS::DynamicType_ptr type,  ::Hello::Basic_Message& value);

template <>
Hello_Export const  ::Hello::Basic_Message* get_dynamic_data_adapter_value< ::Hello::Basic_Message,  ::Hello::Basic_Message>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End STRUCT: Basic_Message */

/* End MODULE: Hello */
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif /* OPENDDS_IDL_GENERATED_BASIC_MESSAGETYPESUPPORTIMPL_H_OHXLJO */
